# Do not change version. This is the version of aws buildspec, not the version of your buldspec file.
version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
  build:
    commands:
      - echo Build started on `date`
      - npm install
      - CI=true npm run test
      - npm run build  
      - npm install --global serve
      - serve -s build
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Build stoped
artifacts:
  files:
    - 'build/*'
