version: 0.2
phases:
  build:
    commands:
      - npm install -g yaml-lint
      - sudo yum update -y
      - sudo yum install -y unzip
      - curl -fsSL https://releases.hashicorp.com/terraform/0.15.0/terraform_0.15.0_linux_amd64.zip -o terraform.zip
      - unzip terraform.zip -d /usr/local/bin/
      - cd IaC
      - terraform version
      - terraform init
      - terraform plan
      - terraform apply --auto-approve
  post_build:
    commands:
      - echo "AWS wait for me I'm coming"